services:
  server:
    build:
      context: ./server
      target: Prod
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./env:/app/.env
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6969:6969"
